name: Haskell CI

on:
  push:
    branches:
    - "**"
    tags-ignore:
    - "**"
  pull_request:
    branches:
    - "**"
    tags-ignore:
    - "**"
    types:
    - 'opened'
    - 'reopened'
    - 'synchronize'

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [macos-10.15, windows-2019, ubuntu-18.04]
    runs-on: ${{matrix.os}}
    steps:
    - name: shim
      shell: bash
      run: |
        ghcup --version
        ghcup config set downloader Curl
        ghcup upgrade
        ghcup --version
